      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v3
        with:
          name: GorillasApp-Linux
          path: out/GorillasApp

      - name: Upload Windows EXE
        uses: actions/upload-artifact@v3
        with:
          name: GorillasApp-Windows
          path: out/GorillasApp.exe

      - name: Upload macOS DMG
        uses: actions/upload-artifact@v3
        with:
          name: GorillasApp-macOS
          path: out/GorillasApp.dmg

