name: Build and Package JavaFX App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install JavaFX
        run: sudo apt install -y openjfx

      - name: Build with Maven
        run: mvn clean package

      - name: Package as AppImage
        run: |
          jpackage \
            --input target \
            --name GorillasApp \
            --main-jar gorillas-1.0-SNAPSHOT.jar \
            --module-path /usr/share/openjfx/lib \
            --add-modules javafx.controls,javafx.fxml \
            --type app-image \
            --dest out/
      
      - name: Upload Linux AppImage
        uses: actions/upload-artifact@v3
        with:
          name: GorillasApp-Linux
          path: out/GorillasApp

