name: Build and Package JavaFX App

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-all:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Maven build
        run: |
          mvn clean package

      - name: Copy JavaFX dependencies
        run: |
          mvn "dependency:copy-dependencies" "-DincludeGroupIds=org.openjfx" "-DoutputDirectory=target/javafx-lib"

      - name: Package as app-image
        run: |
          jpackage --input target --name GorillasApp --main-jar gorillas-1.0-SNAPSHOT.jar --module-path target/javafx-lib --add-modules javafx.controls,javafx.fxml --type app-image --dest out/ --vendor "Otter Knight"

      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Gorillas-${{ matrix.os }}
          path: out/GorillasApp${{ matrix.os == 'macos-latest' && '.app' || '' }}

